# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warrensbox/falcon-form

    steps:
      - checkout

  update-website:
    docker:
      - image: warrensbox/go-rb-py-aws

    steps:
      - checkout
      - run: 
          command: |
            echo $GITHUB_TOKEN
            cd docs; bundle update --bundler; gem install bundler:1.16.2; bundle install --path vendor/bundler; bundle exec jekyll build -c _config.yml; cd ..
            make upload   

  release:
    docker:
      - image: warrensbox/go-rb-py-aws

    steps:
      - checkout
      - run: 
          command: |
            set +e
            source version
            export RELEASE_VERSION; 
            RELEASE_VERSION=$RELEASE_VERSION.${CIRCLE_BUILD_NUM}
            export RELEASE_VERSION;
            echo $RELEASE_VERSION
            git config user.email "warren.veerasingam@gmail.com"
            git config user.name "warrensbox"
            git tag -a ${RELEASE_VERSION} -m "Release Version"
            git push origin ${RELEASE_VERSION}
            curl -L https://git.io/goreleaser | VERSION=v0.76.1 bash
            make publishcircle
            echo $GITHUB_TOKEN
            cd docs; bundle install --path vendor/bundler; bundle exec jekyll build -c _config.yml; cd ..
            make upload   

         
workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - update-website:
          requires:
            - build
          filters:
            branches:
              only: 
              - master
      - release:
          requires:
            - update-website
          filters:
            branches:
              only: 
              - release





