# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warrensbox/falcon-form

    steps:
      - checkout


  release:
    docker:
      - image: warrensbox/go-rb-py-aws

    steps:
      - checkout
      - run: 
          command: |
            make publishcircle
            cd docs; bundle install --path vendor/bundler; bundle exec jekyll build -c _config.yml; cd ..
            make upload
         
workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: 
              - master





