# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/warrensbox/terraform-switcher

    steps:
      - checkout


  release:
    docker:
      - image: warrensbox/go-aws-ubuntu:0.1.0

    steps:
      - checkout
      - run: 
          command: |
            make publishcircle

workflows:
  version: 2

  build_and_test:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: 
              - master

